bpe:
  num_process: 4
  vocab_size: 10000
  special_tokens: ["<|endoftext|>"]
  vocab_path: "outputs/artifacts/vocab.txt"
  merge_path: "outputs/artifacts/merges.txt"

data:
  owt_train_path: "data/owt_train.txt"
  owt_valid_path: "data/owt_valid.txt"
  TinyStories_train_path: "data/TinyStoriesV2-GPT4-train.txt"
  TinyStories_valid_path: "data/TinyStoriesV2-GPT4-valid.txt"

transformer:
  RMSNorm_eps: 0.00001

adamw:
  lr: 0.001
  beta1: 0.9
  beta2: 0.95
  weight_decay: 
  eps: 0.00000001
