bpe:
  num_process: 8
  vocab_size: 32000
  special_tokens: ["<|endoftext|>"]
  vocab_path: "outputs/artifacts/TinyStory_vocab.txt"
  merge_path: "outputs/artifacts/TinyStory_merges.txt"

data:
  owt_train_path: "data/owt_train.txt"
  owt_valid_path: "data/owt_valid.txt"
  TinyStories_train_path: "/xts001/TinyStoriesV2-GPT4-train.txt"
  TinyStories_valid_path: "/xts001/TinyStoriesV2-GPT4-valid.txt"
  training_token_path: "/xts001/training_tokens.txt"

transformer:
  RMSNorm_eps: 0.00001

adamw:
  lr: 0.001
  beta1: 0.9
  beta2: 0.95
  weight_decay: 0.01
  eps: 0.00000001

model:
  vocab_size: 1000
  context_length: 512
  num_layers: 12 
  d_model: 2048
  num_heads: 8
  d_ff: 256
  rope_theta: 10
  device: None
  dtype: None

training:
  steps: 1000
  eval_every: 100
  save_every: 100
  save_dir: "./output"
  batch_size: 4
